name: lpd
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - torch
  - scipy
  - matplotlib
  - scikit-learn
  - h5py
  - tqdm
  - scikit-image
  - medpy
  - pip
  - pip:
    - medpy